databases:
  - name: eatn
    databaseName: eatn
    user: eatn

services:
  - type: web
    name: eatn
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: eatn
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false